models:
  gpt-oss-20b-it:
    backend: vllm
    backend_url: "http://host.docker.internal:8000"
  gpt-oss-20b:
    backend: llamacpp
    backend_url: "http://host.docker.internal:8002"
    embeddings: true
